language: ruby
cache: bundler
script: bundle exec middleman build
before_install:
  - nvm install 14
deploy:
  provider: cloudfoundry
  api: https://api.london.cloud.service.gov.uk
  username: tech-doc-tool+paas-bot@digital.cabinet-office.gov.uk
  password:
    secure: HErlbjKAGojnv3TyeqoSd0YvoKIXBCv+y7V9aOULyCFPhMXmGmgZE6OTUNVMwmDBPc9RVzTF8kHtxHD5XyKf0SZLxV2KMBk4rtSmKOKvvgtGV9SoYbQHA/k8mlKBlEEiltIH4X+aiGPOZHY8rE7brUmHuRf99K24rYjP6lqymrGoF8SHDy94ILWG2qc7Gh28BPsWbUTiO1U2Y4hU0T1xQtvcA8UfYwlmC7Dggp6SudD+ELi1mfZhmr3qER9eB77yoO1SPn2ma+LtD8zTVABCDp1wqdQ3WQGzv1Xk/2pl9FOnx0Bv3XzRxgIJhi4T2PyfeLD2HzG42LJAY9ai6w8qC/P6NpkVwUq0jWbpie76XuvkyVswKqWN9KEBOHaZ02aa1XIxpZ7JBhu7BCZQ+qOGQ+Z4g7kL9I18pIvMyZ/+WlZRd7dRIDr8Hh+aYXXSHWt6n7xu4ELRQ9E0Jxrx3h6zMhoFpyuCmvGdFplgvaonhfxCoVHrdQaJ5MblX4TQhwMUJEtk87DCDnusnK42ZjXezx8uAINDK+WZrQV96C8PLsgvvlhHiSzh80xOzvhMbtdzm7djKnKQWLm60XcYbUivwuW5BhCb4K9G2OGxQb2Pn3UKLWzpteqNup6EIvu1Ue0tjnjwSDHbT/ILvRIaDvIzwO8cPudvYL+m9EYYyXNYIXc=
  organization: gds-tech-writers
  space: sandbox
  on:
    repo: alphagov/tdt-documentation
